# Generated by Django 4.0.3 on 2022-03-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationApp.category'),
        ),
    ]
