# Generated by Django 4.0.3 on 2022-03-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0002_bus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
